techlinx/Blog/urls.py
from django.conf.urls import url
from django.contrib import admin
from .views import index,post,add_comment

urlpatterns = [
    url(r'^$', index,name="index"),
    url(r'^posts/(?P<slug>[\w-]+)/$', post,name="post"),
    url(r'^comment/(?P<slug>[\w-]+)/$', add_comment, name="add_comment"),
]

techlinx/Staff/urls.py
from django.conf.urls import url
from django.contrib import admin
from .views import autor


urlpatterns = [
    url(r'^(?P<slug>[\w-]+)/$', autor,name="detail"),
    
]

techlinx/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^jet/', include('jet.urls', 'jet')),  # Django JET URLS
    url(r'^', include("techlinx.Blog.urls",namespace="blog") ),
    url(r'^autor/', include("techlinx.Staff.urls",namespace="autores") ),
    url(r'^summernote/', include('django_summernote.urls')),
]
if settings.DEBUG:
     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

techlinx/Blog/models.py
from django.db import models
from uuid import uuid4
from django.utils.text import slugify
from datetime import datetime
# Create your models here.

def path_save_images(instance,filname): #TODO DRY
    return "{0}/{1}".format(instance.slug,filname)

class Categories(models.Model):
    id = models.UUIDField(primary_key = True,
        unique = True,
        default = uuid4,
        editable = False)

    nombre =  models.CharField(max_length = 150,
        help_text="Nombre de la categoria")

    slug = models.SlugField(max_length = 200,
        unique = True,
        help_text = "Slug de url del post")

    imagen = models.ImageField(upload_to=path_save_images,
        help_text="Imagen de la categoria")



    def _get_unique_slug(self):
        slug = slugify(self.nombre)
        unique_slug = slug
        num = 1
        while Categories.objects.filter(slug=unique_slug).exists():
            unique_slug = '{}-{}'.format(slug, num)
            num += 1
        return unique_slug
    def _get_published_date(self):
        return datetime.now()

    @models.permalink
    def get_absolute_url(self):
        return 'blog:category', (self.slug,)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = self._get_unique_slug()
        super().save()

    def __str__(self):
        return "Categoria: {}".format(self.nombre)

class Post(models.Model):

    id = models.AutoField(primary_key = True,
        unique = True)
    titulo = models.CharField(max_length = 150,
        help_text="Titulo del Post")
    slug = models.SlugField(max_length = 200,
        unique = True,
        help_text = "Slug de url del post")
    contenido = models.TextField(help_text="Contenido del Post")
    cover = models.ImageField(upload_to=path_save_images,
    help_text = "Imagen de cover del post")
    categoria = models.ForeignKey(Categories,
        on_delete = models.SET_NULL,
        blank = True,
        null = True,
        help_text = "Categoria del post",
        related_name = "publicaciones")
    publicado = models.BooleanField(default=False,
        verbose_name = "¿Post publicado?",
        help_text = "Check si post esta publicado")
    fecha_creacion = models.DateField(auto_now_add=True,
        help_text = "Fecha en que se creo el post")
    fecha_publicacion = models.DateField(null=True,
        blank=True,
        help_text = "Fecha en la que se publico el post"
    )
    tiempo_estimado = models.IntegerField(
        help_text = "Tiempo aproximado de lectura del post",
        default = 0
    )
    autor = models.ForeignKey("Staff.Staff",
        on_delete=models.CASCADE,
        help_text="Usuario Autor",
        null=True,
        related_name="publicaciones")

    def _get_unique_slug(self):
        slug = slugify(self.titulo)
        unique_slug = slug
        num = 1
        while Post.objects.filter(slug=unique_slug).exists():
            unique_slug = '{}-{}'.format(slug, num)
            num += 1
        return unique_slug

    def _get_published_date(self):
        return datetime.now()

    def _get_average_reading(self):
        WPM = 180 #Tiempo aproximado en el que una persona lee palabras
        num_words = len(self.contenido.split(" ")) #TODO Checar si hay tags u otro tipo de cosas que afecten el calculo
        return int(num_words/WPM)

    @models.permalink
    def get_absolute_url(self):
        return 'blog:post', (self.slug,)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = self._get_unique_slug()
        if self.publicado and not self.fecha_publicacion:
            self.fecha_publicacion = self._get_published_date()
        self.tiempo_estimado = self._get_average_reading()
        super().save()

    def __str__(self):
        return "Post: {0}".format(self.titulo)

#Aqui van los Comentarios 11/11/2018
class Comment(models.Model):
    post = models.ForeignKey(Post, related_name='comments')
    user = models.CharField(max_length=200)
    email = models.EmailField()
    text = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    approved_comment = models.BooleanField(default=False)

    def approved(self):
        self.approved = True
        self.save()

    def __str__(self):
        return self.text

#Caja de Comentario 08/11/
#class Comment(models.Model):
#        Post= models.ForeignKey('blog.Post', on_delete=models.CASCADE, releated_name="comments")
#        author= models.CharField(max_length=200)
#        text = models.TextField()
#        create_date = models.DateTimeField(default=tiemezone.now)
#        approved_comment = models.BooleanField(default=False)

#        def approve(self):
#            self.approved_comment = True
#            self.save()

#        def __str__(self):
#            return self.text

techlinx/Staff/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify

import uuid
# Create your models here.

def path_save_images(instance,filname):
    return "{0}/{1}".format(instance.slug,filname)

class Staff(models.Model):
    id = models.UUIDField(primary_key = True,
        unique = True,
        editable = False,
        default = uuid.uuid4 )
    user = models.OneToOneField(User,
        on_delete=models.CASCADE,
        related_name = "usuario"
    )
    slug = models.SlugField(max_length=180, 
        unique = True)
    biografia = models.TextField(help_text="Biografia del miembro del Staff")
    imagen = models.ImageField(
        upload_to=path_save_images,
        help_text="Imagen del miembro del staff"
    )
    autor = models.BooleanField(verbose_name="¿Es autor?",
        default = False,
        help_text = "Marcar si es autor")
    editor = models.BooleanField(verbose_name="¿Es Editor?",
        default = False,
        help_text = "Marcar si es Editor")
    facebook = models.URLField(verbose_name="Perfil de Facebook",
        help_text = "URL del Perfil de Facebook", 
        null = True,
        blank = True )
    twitter = models.URLField(verbose_name="Perfil de Twitter",
        help_text = "URL del Perfil de Twitter", 
        null = True,
        blank = True )
    GitHub = models.URLField(verbose_name="Perfil de GitHub",
        help_text = "URL del Perfil de GitHub", 
        null = True,
        blank = True) 
    pagina_personal = models.URLField(verbose_name="Pagina personal",
        help_text = "URL del Perfil de pagina personal", 
        null = True,
        blank = True)

    def _get_unique_slug(self):
        slug = slugify(self.user.username)
        unique_slug = slug
        num = 1
        while Staff.objects.filter(slug=unique_slug).exists():
            unique_slug = '{}-{}'.format(slug, num)
            num += 1
        return unique_slug
    
    def __str__(self):
        if self.autor:
            return "Autor: "+self.user.username
        elif self.editor:
            return "Editor: "+self.user.username
        else:
            return "Staff: "+self.user.username

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = self._get_unique_slug()
        super().save()

    @models.permalink
    def get_absolute_url(self):
        return 'autores:detail', (self.slug,)
 
    
    
    






   

techlinx/Blog/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('user', 'email', 'text','post','approved_comment')

techlinx/Blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import JsonResponse
from .models import Post, Categories, Comment
from django.db.models import Q
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import CommentForm

# Create your views here.


def index(request):
    imagen = "/static/img/sidebar.jpg"
    posts_list = Post.objects.filter(publicado=True).select_related(
        'autor').order_by('-fecha_publicacion')
    categories = Categories.objects.all()
    paginator = Paginator(posts_list, 5)
    page = request.GET.get('page', 1)
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        posts = paginator.page(paginator.num_pages)

    return render(request, 'blog/index.html', {'image': imagen, 'posts': posts, 'categories': categories})


def post(request, slug):

    post = get_object_or_404(Post, slug=slug)
    print('post: ' + post.titulo)
    related = Post.objects.filter(Q(categoria=post.categoria) | Q(
        autor=post.autor), ~Q(titulo=post.titulo))[:3]
    return render(request, 'blog/post/post.html', {'post': post, 'related': related})


def add_comment(request, slug):
	post = get_object_or_404(Post, slug=slug)
	print(request.POST)
	if request.method == 'POST':
		return JsonResponse({"prueba": request.POST.get("text")})


# 13/11/2018 agregado este comando primera parte
# def categories(request, idcategory):
#    categories = Categories.objects.get(id=idcategories)
#    posts = categories.post_set.order_by("-creation_date")

#    return render_to_response(
#        "home.html",
#        {
#            "posts":posts,
#        },
#    )

# def categories(request):
#    categories = Categories.objects.all()
#    return render(request, 'blog/categorias/index.html',{'categories':categories})

# def categories(request, pk):
#    categories = get_object_or_404(Categories, pk=pk)
#    return render(request, 'blog/base.html',{'categories':categories})

techlinx/Staff/views.py
from django.shortcuts import render, get_object_or_404
from .models import Staff
# Create your views here.


def autor(request,slug):
    autor = get_object_or_404(Staff,slug=slug)
    image = "/static/img/sidebar.jpg"
    publicaciones = autor.publicaciones.all().order_by('-fecha_publicacion')[:4]
    return render(request,'blog/autores/perfil.html',{'autor':autor,'image':image,'publicaciones':publicaciones})

techlinx/templates/blog/post/add_comment.html
{% extends "blog/post/base-post.html" %}
{% block content %}
  <h1>Añadir nuevo comentario</h1>
  <form method="POST">{% csrf_token %}
    {{ form.as_p}}
    <button type="submit">Submit</button>
  </form>
{% endblock %}

techlinx/templates/blog/post/base-post.html
{% load static %}
<!DOCTYPE html>
<html class="no-js">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>{% block title %}

        {% endblock title %}</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width">

        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/main.css' %}">

        <!--[if lt IE 9]>
            <script src="/js/vendor/html5shiv.min.js"></script>
        <![endif]-->
        <link rel="stylesheet"
        href="//cdn.jsdelivr.net/gh/highlightjs/cdn-release@9.12.0/build/styles/agate.min.css">
        <script src="//cdn.jsdelivr.net/gh/highlightjs/cdn-release@9.12.0/build/highlight.min.js"></script>
        <script src="{% static 'js/vendor/modernizr.custom.32229-2.8-respondjs-1-4-2.js' %}"></script>
        <style>
            pre { font-size: 2em !important;}
        </style>
    </head>
    <body>
        <!-- if the user has javascript disabled they can still use the menu -->
        {% block content %}
      <!--13/11/2018 antes antes habia un block y un enblock -->
        {% endblock content %}

        <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
        <script>window.jQuery || document.write('<script src="js/vendor/jquery-1.11.2.min.js"><\/script>')</script>

        <script src="{% static 'js/vendor/jquery.jpanelmenu.min.js' %}"></script>
        <script src="{% static 'js/vendor/bootstrap.min.js' %}"></script>
        <script src="{% static 'js/vendor/fastclick.min.js' %}"></script>
		
		{% block js %}
			
		{% endblock js %}
			

        <script src="{% static 'js/main.js' %}"></script>
        <script>
            $(document).ready(function() {
                $('pre').each(function(i, block) {
                  hljs.highlightBlock(block);
                });
              });
        </script>
    </body>
</html>

techlinx/templates/blog/post/footer-post.html
{% load bitly %}
        <footer class="single">
            <div class="container">
                <div class="row">
                    <div class="col-xs-12 col-md-2">
                        <img src="{{post.autor.imagen.url}}" class="user-icon " alt="user-image">
                    </div>
                    <div class="col-xs-12 col-md-6">
                        <div class="category-list">
                            <p>Publicado <span>{{post.fecha_publicacion}}</span></p>
                            <p><a href="#">{{post.autor.user.first_name}} {{post.autor.user.last_name}}</a> in <a href="#">{{post.categoria.nombre}}</a></p>

                        </div>
                    </div><!-- end col -->
                    <div class="col-xs-12 col-md-4">
                        <div class="social">
                            <p>Compartir con: </a>
                            <div class="social-links">
                                <a class="social-icon" href="#"><i class="fa fa-twitter"></i></a>

                                <a class="social-icon" href="https://www.facebook.com/sharer/sharer.php?u={{ request.build_absolute_uri }}" data-platform="facebook" data-message="Message about this post" data-url="http://bit.ly/2JplFhg={{ request.build_absolute_uri }}"><i class="fa fa-facebook-official"></i></a>

                                <a class="social-icon" data-platform="mail"  href="mailto:support@writertheme.com"><i class="fa fa-envelope"></i></a>
                            </div>
                        </div>
                    </div>
                </div><!-- end row -->
            </div>
            {% comment "v2" %}
            <div class="row read-another-section">
                <div class="col-6 col-md-2 no-gutter read-another-container">
                  <a href="post.html">
                    <div class="overlay"></div>
                    <img src="img/square-iceland.jpg">
                    <h3 class="read-another">Land of Fire &amp; Ice</h3>
                  </a>
                </div>
                <div class="col-6 col-md-2 no-gutter read-another-container">
                <a href="post.html">
                    <div class="overlay"></div>
                    <img src="img/square-spain.jpg">
                    <h3 class="read-another">The Coast of Your Mind</h3>
                </a>
                </div>
                <div class="col-6 col-md-2 no-gutter read-another-container">
                  <a href="post.html">
                    <div class="overlay"></div>
                    <img src="img/square-peak.jpg">
                    <h3 class="read-another">Get Out of Your Comfort Zone</h3>
                  </a>
                </div>
                <div class="col-6 col-md-2 no-gutter read-another-container">
                    <a href="post.html">
                    <div class="overlay"></div>
                    <img src="img/square-woods.jpg">
                    <h3 class="read-another">Not All Who Wander Are Lost</h3>
                    </a>
                </div>
                <div class="col-6 col-md-2 no-gutter read-another-container">
                    <a href="post.html">
                    <div class="overlay"></div>
                    <img src="img/square-sunset.jpg">
                    <h3 class="read-another">Open Your Mind</h3>
                    </a>
                </div>
                <div class="col-6 col-md-2 no-gutter read-another-container">
                    <a href="post.html">
                    <div class="overlay"></div>
                    <img src="img/square-mountain.jpg">
                    <h3 class="read-another">Ten Reasons to Hike</h3>
                    </a>
                </div>
            </div>
            {% endcomment %}

        </footer>

techlinx/templates/blog/post/header-post.html
<header class="hero-image" role="banner" style="background-image: url({{url}});">

    <span class="menu-trigger animated fadeInDown">
        <span class="bar"></span>
        <span class="bar"></span>
        <span class="bar"></span>
    </span>


    <div id="menu-target">
        <ul>
            <li><i class="fa fa-home"></i><a href="index.html">Home</a></li>
            <li><i class="fa fa-user"></i><a href="author.html">John Smith</a></li>
            <li><i class="fa fa-anchor"></i><a href="page.html">About</a></li>
            <li><i class="fa fa-star"></i><a href="favorites.html">Favorites</a></li>
            <li><i class="fa fa-paper-plane"></i><a href="contact.html">Contact</a></li>
        </ul>
        <hr>
        <ul>
            <li><i class="fa fa-file"></i><a href="post.html">Post Page</a></li>
            <li><i class="fa fa-file"></i><a href="post-sidebar.html">Post with Sidebar</a></li>

            <li><i class="fa fa-home"></i><a href="alt-home.html">Alternate Home</a></li>
            <li><i class="fa fa-image"></i><a href="category.html">Category Page</a></li>
        </ul>
    </div>
</header>

techlinx/templates/blog/post/post.html
{% extends "blog/post/base-post.html" %}
{% load static %}

{% block content %}

{% include "blog/post/header-post.html" with url=post.cover.url %}

<main class="container">
	<div class="row">
		<div class="col-12 col-lg-8 single-content-sidebar">
			<h1>{{post.titulo | upper}}</h1>
			<p class="meta">

			</p>

			{{post.contenido |safe}}
			<!--<div class="comentarios">
                    <textarea name="comentarios" rows="10" cols="40">Escribe tus comentarios</textarea>
            </div>-->
			<!--22/11/2018 Caja de Comentarios de Facebook-->
			<div class="fb-like" data-href="https://developers.facebook.com/docs/plugins/" data-layout="standard" data-action="like"
			 data-size="small" data-show-faces="true" data-share="true"></div>
			<div class="fb-comments" data-href="https://developers.facebook.com/docs/plugins/comments#configurator"
			 data-numposts="5"></div>
			<div id="fb-root"></div>
			<script>(function (d, s, id) {
					var js, fjs = d.getElementsByTagName(s)[0];
					if (d.getElementById(id)) return;
					js = d.createElement(s); js.id = id;
					js.src = 'https://connect.facebook.net/es_LA/sdk.js#xfbml=1&version=v3.2';
					fjs.parentNode.insertBefore(js, fjs);
				}(document, 'script', 'facebook-jssdk'));</script>

			<!--Aqui van los Comentarios 11/11/2018 -->


			<hr>
			{% for comment in post.comments.all %}
			<div class="comment">
				<p>Comentarios: {{ post.comments.count }}</p>
				<!--12/11/2018-->
				<div class="date"> Fecha de Creacion: {{ comment.created }}</div>
				<a href="{% url 'blog:post' slug=post.slug %}"> Nuevo Comentario</a>
				<p>Written by {{post.author}} on {{post.published}}</p>
				<p>{{comment.user}}</p>
				<p>{{ comment.text|linebreaks }}</p>

			</div>
			{% empty %}
			<p>No Hay Comentarios :(</p>
			{% endfor %}



			<h1>Añadir nuevo Comentario</h1>
			<form id="new_comment_user" method="POST">
				{% csrf_token %}
				<p>
					<label for="id user">User:</label>
					<input id="id_user" type="text" name="user" required="" maxlength="200">
				</p>
				<p>
					<label for="id email">Email:</label>
					<input id="id_email" type="email" name="email" required="" maxlength="254">
				</p>
				<p>
					<textarea id="id_text" name="text" required="" rows="10" cols="40"></textarea>
				</p>
				<style media="screen">
					.btn{
      height: 40px;
      width: 200px;
      border-radius: 25px;
      background-color: #CC9933;
      box-shadow: 0 2px 4px 0 rgba(0,0,0,0.3);
      color: white;
    }
  </style>
				<button type="submit" name="button" class="btn">Submit</button>
			</form>

			


		</div><!-- main-content/col -->

		<div class="col-12 col-lg-3 ml-auto single-content-sidebar-area">

			<img src="{{post.autor.imagen.url}}" class="user-icon " alt="user-image">
			<div class="meta">

				<div class="sidebar-info">
					<a class="" href="category.html">{{post.autor.user.first_name}} {{post.autor.user.last_name}}</a> in <a href="category.html">{{post.categoria.nombre}}</a>
				</div>

				<div class="sidebar-readtime">
					<i class="fa fa-bookmark"></i> {{post.tiempo_estimado}} minuto(s) de lectura
				</div>

			</div>


			{% if related %}
			<h2 class="favorites">Posts Similares</h2>

			{% for post in related %}
			<div class="similar-post">
				<a href="{{post.get_absolute_url}}">
					<h3>{{post.titulo}}</h3>
				</a>
			</div>
			{% endfor %}

			{% endif %}



		</div>

	</div>
	<!--/row -->

</main> <!-- /container -->


{% include "blog/post/footer-post.html" with post=post %}

{% endblock content %}


{% block js %}
<script type="text/javascript">
	var csrftoken = $("[name=csrfmiddlewaretoken]").val();

	function csrfSafeMethod(method) {
		// these HTTP methods do not require CSRF protection
		return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
	}


	$('#new_comment_user').on('submit', function (e) {
		e.preventDefault();
		var form = $(this);

		$.ajaxSetup({
			beforeSend: function (xhr, settings) {
				if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
					xhr.setRequestHeader("X-CSRFToken", csrftoken);
				}
			}
		});

		$.ajax({
			type: 'POST',
			url: '/comment/'+'{{post.slug}}/',
			data:form.serialize(),
			sucess: function (response) {
				cosnole.log(response.data)
				alert("nuevo comentario");

			}
		});
	});
</script>	

{% endblock js %}
	